kind: Service
apiVersion: v1
metadata:
  name: user-svc
  labels:
    app: user-svc
spec:
  type: LoadBalancer
  selector:
    app: user-svc
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: user-svc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-svc
        version: v1
    spec:
      containers:
        - name: user-svc
          image: iad.ocir.io/natdcshjumpstartprod/user_catalog:{{BUILD_NUMBER}}
          command: ["java", "-jar"]
          args:
            - "-Ddatasource.username=$(DB_USER)"
            - "-Ddatasource.password=$(DB_PASSWORD)"
            - "-Ddatasource.url=$(DB_URL)"
            - "user-svc.jar"
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: user-svc-secrets
                  key: dbUser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-svc-secrets
                  key: dbPassword
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: user-svc-secrets
                  key: dbUrl
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
---
